In [2]:
import torch
import numpy as np

## 1. 初始化张量

In [12]:
## from list
data = [[1.2, 3.4], [5.6, 7.8] ]
b = torch.tensor(data)
b # list浮点型默认32位置

tensor([[1.2000, 3.4000],
        [5.6000, 7.8000]])

In [8]:
## from data
data = np.random.normal(size=(3, 4))
b = torch.tensor(data) # numpy浮点型默认32位置
b

tensor([[ 0.2706, -1.0028,  0.7837,  0.1853],
        [-0.3537, -0.3422,  2.4865,  0.7937],
        [-0.0182,  0.6812,  0.7404, -0.7705]], dtype=torch.float64)

In [16]:
## from tensor
c = torch.zeros_like(b)
c = torch.ones_like(b)
c = torch.rand_like(b)

d = torch.rand(size=(1, 2))
c, d, c.dtype# 没有给出dtype

(tensor([[0.5540, 0.9821],
         [0.6026, 0.7963]]),
 tensor([[0.9550, 0.2753]]),
 torch.float32)

## tensor的属性

In [18]:
c.dtype, c.shape, c.device # 

(torch.float32, torch.Size([2, 2]), device(type='cpu'))

## Tensor的操作

In [19]:
# move to GPU
if torch.cuda.is_available():
    tensor = c.to('cuda')

In [22]:
torch.is_tensor(c), torch.is_floating_point(c)

(True, True)

In [24]:
a = torch.tensor(1.0)
torch.is_nonzero(a) # 只能是标量

True

In [30]:
torch.numel(c), c.shape # 张量中的元素个数

(4, torch.Size([2, 2]))

In [32]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [39]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [49]:
torch.linspace(0.0, 10.0, 3)

tensor([ 0.,  5., 10.])

In [50]:
torch.full([2, 2], 5)

tensor([[5, 5],
        [5, 5]])

In [4]:
x = torch.rand((2, 2))
y = torch.rand((2, 3))

torch.cat([x, y], dim=1) # 0是列，1是行

tensor([[0.7552, 0.3886, 0.8948, 0.3579, 0.3269],
        [0.8281, 0.7283, 0.8207, 0.5161, 0.9151]])

In [12]:
b = torch.rand((3, 2))
torch.chunk(b, chunks=2, dim=0)  # chunks：沿着dim分割后张量的个数
torch.split(b, 1, dim=0)         # 1     : 沿着dim分割后张量的维度

(tensor([[0.4212, 0.2813]]),
 tensor([[0.6282, 0.9102]]),
 tensor([[0.4870, 0.0274]]))

In [17]:
b = torch.randn((3, 1, 2))
c = torch.squeeze(b) #移除所有维度大小为1的维度
b.shape, c.shape

(torch.Size([3, 1, 2]), torch.Size([3, 2]))

In [19]:
src = torch.rand((2, 3))
src, torch.take( src, torch.tensor([0, 2, 5]) ) # src转换成1维，按照index去取

(tensor([[0.2291, 0.8841, 0.5051],
         [0.7631, 0.4059, 0.5992]]),
 tensor([0.2291, 0.5051, 0.5992]))

In [29]:
# 第一个维度复制2份，第二个维度复制两份
# 整个复制，不是单个元素复制
torch.tile(src, dims=(2, 2))


tensor([[0.2291, 0.8841, 0.5051, 0.2291, 0.8841, 0.5051],
        [0.7631, 0.4059, 0.5992, 0.7631, 0.4059, 0.5992],
        [0.2291, 0.8841, 0.5051, 0.2291, 0.8841, 0.5051],
        [0.7631, 0.4059, 0.5992, 0.7631, 0.4059, 0.5992]])

In [31]:
src.unbind(dim=1) # 按行列分割成单个tensor

(tensor([0.2291, 0.7631]), tensor([0.8841, 0.4059]), tensor([0.5051, 0.5992]))

In [33]:
torch.unsqueeze(src, dim=0).shape # 在dim位置加一个维度大小为1的维度

torch.Size([1, 2, 3])

In [35]:
x = torch.randn((3, 2))
y = torch.ones((3, 2))
torch.where(x>0, x, y) # 相当于是一个张量版的3目运算符

tensor([[1.0000, 1.2689],
        [1.0000, 0.4842],
        [0.3533, 0.0265]])

## 随机种子的设定

In [36]:
torch.manual_seed(20) # GPU CPU都可以用

In [41]:
torch.bernoulli( torch.rand((3, 3)) )

tensor([[0., 1., 1.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [50]:
torch.normal(0, 1, size=(4, 2) )

tensor([[-0.2679, -0.2224],
        [-0.2564, -1.4328],
        [ 0.2383,  0.3659],
        [-0.8168,  1.0536]])

In [51]:
torch.randperm(4)

tensor([0, 2, 3, 1])